### ISSUE TITLE
New feature to measure voltage "sag".

### ISSUE THREAD

**Issue by elisabettai** [BlueBrain/eFEL#101]
Would it be possible to implement a feature called "sag_ratio? A common definition according to [NeuroElectro.org](http://neuroelectro.org/ephys_prop/34/), could be: "Ratio between the steady state decrease in the voltage and the largest decrease in voltage following a hyperpolarizing current step"

I think we can assume to have a hyperpolarizing current step.
For the implementation, I see two potential ways:

1. Use the features "voltage_deflection", "minimum_voltage", "voltage_base" which already exist, then:
 sag_ratio = (minimum_voltage - voltage_deflection)/(minimum_voltage - voltage_base). From the source code, it seems that "minimum_voltage" computes the absolute minimum between stim_start and stim_end.

2. Instead of using the absolute minimum, using a (time) window to get more robust estimate of the peak, similar to the "estimate_sag" function in the [AllenSDK](http://alleninstitute.github.io/AllenSDK/_modules/allensdk/ephys/ephys_extractor.html#EphysCellFeatureExtractor). For example they compute the mean voltage between **t[peak_index] - peak_width / 2.** and  **t[peak_index] + peak_width / 2.** with peak_index = 0.005 sec.

This issue actually started from [here](https://github.com/BlueBrain/eFEL/issues/98). I have incorrectly thought that the "voltage_deflection_begin" was giving the value of ("minimum_voltage" - "voltage_base").

**Comment by wvangeit** [comment]
Ok, sounds good.
There seems to be a discrepancy between the Allen definition of this ratio and neuroelectro definition.
If I read it correctly, neuroelectro seems to be:
(voltage_base - steady_state) / (voltage_base - min_voltage)
While allensdk:
(min_voltage - steady_state) / (min_voltage - voltage_base).
Any preference ?

Regarding the average calculate. Can implement the two, like sag_ratio and sag_ratio_avg

**Comment by wvangeit** [comment]
Actually, the more you look at this, the more it seems like a nice non-standardized term in ephys.
E.g.
http://neuroelectro.org/data_table/1324/
based on http://jn.physiology.org/content/79/3/1518.long
"
 “Sag” was quantified by the ratio of the steady state voltage to the peak voltage in response to current injections of −50 to −300 pA.
"

Another definition .... (but all appear in the same table on neuroelectro.org)

**Comment by elisabettai** [comment]
Yes, it's a very nice example of non-standardized term. An ontology could solve that, but as far as I know there's no ontology for ephys terms.

I would go with the allensdk definition. I also wonder if it makes more sense to have it as a ratio or amplitude. 

For the average, do you mean different way to estimate the minimum_voltage (absolute minimum vs. average over a small time window)? I'm ok with having the two features.

**Comment by elisabettai** [comment]
![sag_feature](https://user-images.githubusercontent.com/18575092/27189174-db44df34-51f0-11e7-9fde-47ba36857278.png)

**Comment by elisabettai** [comment]
![sag_features](https://user-images.githubusercontent.com/18575092/27190906-4b0dac9c-51f6-11e7-90a0-80187eff348e.png)


What about having these features:

- **sag_amplitude**: steady_state - minimum_voltage
- **sag_ratio1**: (minimum_voltage-steady_state) / (minimum_voltage - voltage_base), should be like in allesdk
- **sag_ratio2**: (steady_state-voltage_base) / (minimum_voltage - voltage_base). It's equivalent to the neuroelectro one, I've just inverted the signs, so that it's easier to compare with "sag_ratio".

The name "steady_state" may not be the appropriate for eFEL, I hope the figure it's clear to specify the desired quantity.

**Comment by wvangeit** [comment]
@elisabettai, I implemented the features you requested and added documentation.
One thing to be aware of: eFEL will throw error when sag_amplitude is calculated on trace that has a positive voltage deflection, I thought this was better than to fail silently.
Let me know if everything works as expected.

**Comment by elisabettai** [comment]
@wvangeit, the sag features seem to work as expected. For now I think it's fine to have errors when the trace has a positive voltage deflection.
