### ISSUE TITLE
voltage_base calc is wrong

### ISSUE THREAD

**Issue by mbezaire** [BlueBrain/eFEL#104]
Calculation for voltage_base is wrong. There is a clue to this in the documentation, which claims that stim_end is required to calculate the value, when it should not be necessary.

Calculating this on my own code, where the stimulus starts at 530 ms and ends at 1530 ms, I find the mean voltage from 477 to 530 ms is -68 mV.  If I calculate the mean voltage for the last 10% of the time DURING stimulation, from 1377 to 1530 ms, I get -39 mV which is what eFEL reports for the voltage_base property.
________________________
LibV5 : voltage_base

The average voltage during the last 10% of time before the stimulus.

Required features: t, V, stim_start, stim_end
Parameters: voltage_base_start_perc (default = 0.9)
voltage_base_end_perc (default = 1.0)

Units: mV
Pseudocode:

voltage_base = numpy.mean(voltage[numpy.where(
    (t >= voltage_base_start_perc * stim_start) &
    (t <= voltage_base_end_perc * stim_start))])

**Comment by mbezaire** [comment]
@wvangeit

**Comment by wvangeit** [comment]
Would you mind sharing the trace for which you see this behavior ?
It's strange because we have e.g. a test where we calculate:
   voltage_base = numpy.mean(voltage[numpy.where(                                  
        (time >= 0.9 * stim_start) & (time <= stim_start))])
and this give the same result as the efel output.

**Comment by mbezaire** [comment]
Oops, you're right, I hadn't updated the start and end time of the stim. Sorry about that!

**Comment by wvangeit** [comment]
Ok, no problem. Let us know if you find any other issues.
