### ISSUE TITLE
Calculating input resistance - how to provide stimulus info?

### ISSUE THREAD

**Issue by mbezaire** [BlueBrain/eFEL#108]
When I try to access the input resistance feature, I am getting this error message:
/Library/Python/2.7/site-packages/efel/api.py:367: RuntimeWarning: Error while calculating feature ohmic_input_resistance: 
Feature [stimulus_current] is missing

But I don't see a stimulus current feature anywhere, and if I try to request it from the list of features to calculate, I get this error:
Traceback (most recent call last):
  File "MWE.py", line 42, in <module>
    depol_results = efel.getFeatureValues(depoltraces, ['stimulus_current','voltage_base','voltage_deflection','ohmic_input_resistance'])
  File "/Library/Python/2.7/site-packages/efel/api.py", line 314, in getFeatureValues
    map_result = parallel_map(_get_feature_values_serial, traces_featurenames)
  File "/Library/Python/2.7/site-packages/efel/api.py", line 359, in _get_feature_values_serial
    exitCode = cppcore.getFeature(featureName, cppcoreFeatureValues)
TypeError: Unknown feature name

This happened in both versions of efel that I've tried: u'2.11.31' and u'2.11.41'.

More generally, I couldn't see where to provide the stimulus information in the first place. I had thought the trace dict would make sense, but it seems to only expect a time vector, a voltage vector, and the start and end times of the stimulus but not the amplitude of the stimulus that would be needed to calculate the input resistance. Thanks.

**Comment by wvangeit** [comment]
Hi,
Yes, that's confusing indeed.
'stimulus_current' is indeed not a 'Feature', so the message is confusing.
You actually have to set the current value using
efel.setDoubleSetting('stimulus_current', stimulus_current)
For an example see here:
https://github.com/BlueBrain/eFEL/blob/master/efel/tests/test_basic.py#L1091

I'm changing the eFEL code to make the message a bit clearer.

**Comment by wvangeit** [comment]
Addressed by #109
