### ISSUE TITLE
Input Resistance calc

### ISSUE THREAD

**Issue by mbezaire** [BlueBrain/eFEL#110]
Hello, I upgraded to efel-2.11.45, but I still don't have the "E29" feature for calculating input resistance (though E2-E27, E39, E40 are available).  The other feature "ohmic_input_resistance" is extremely off. It seems to be because it uses the "voltage_deflection" feature in the calculation, and that feature seems to be picking up a tiny noise blip at the beginning of the trace (3 mV) and ignoring the 24 mV offset produced by the stimulus later on.
voltage_deflection = 0.0038342857142978914
ohmic_input_resistance = 0.037602023420651907
![image](https://user-images.githubusercontent.com/6456664/29530956-469cbc0e-8674-11e7-8597-a01d2dbf17e2.png)

How can I access the E29 feature or is there a way to fix the voltage_deflection calculation? Thanks.

**Comment by wvangeit** [comment]
Hi,
Yes indeed, it seems the E29 feature was never implemented.
For the trace you're showing I think it's best to use the feature 'ohmic_input_resistance_vb_ssse'.
The old ohmic_input_resistance uses a voltage deflection that will indeed not be correct for your trace.
ohmic_input_resistance_vb_ssse uses voltage_deflection_vb_ssse, which is the voltage difference between the voltage_base (voltage before stimulus) and the steady-steady voltage near the end of the stimulus, which is what you want I guess.

**Comment by wvangeit** [comment]
Actually, so this pointed to where the confusion came from https://github.com/BlueBrain/eFEL/pull/111
The pdf with features still showed E29. At some point this feature was removed because it contained a bug.
Let me know if the ohmic_input_resistance_vb_ssse feature suffices for you.

**Comment by mbezaire** [comment]
It also gives odd results. I printed out several features and am not sure why they are what they are:
![image](https://user-images.githubusercontent.com/6456664/29627638-b79d0e8a-8800-11e7-95fe-63daa4f064f9.png)

Subthreshold Properties
Stimulation = -0.20 nA
ohmic_input_resistance_vb_ssse: -0.211952419379
steady_state_voltage_stimend: -55.8716
voltage_deflection: 0.0226571428571
steady_state_voltage: -59.2440913258
ohmic_input_resistance: 0.112464549058
trace_check: 0
voltage_base: -55.8289
voltage_after_stim: -62.6493842219
voltage_deflection_begin: 0.0287571428571
voltage_deflection_vb_ssse: -0.0427

I'm using units of ms, mV, and nA.

**Comment by wvangeit** [comment]
Hi,
Which values are you worried about ?
The negative input resistance is indeed something that shouldn't happen. Would you mind sharing the raw traces so that I can investigate (and maybe the script you use to generate these values) ?
Visually the other values seem to be correct though.

**Comment by mbezaire** [comment]
Hi, yes the negative input resistance - was I supposed to set the stimulus
current to the absolute value rather than the actual value? Looking at it
again, everything else seems to make sense now.

**Comment by wvangeit** [comment]
The stimulus current should be set to the negative value, so -0.20 nA.
I'm asking, because the code is dividing the voltage_deflection_vb_ssse and the stimulus current to get the ohmic_input_resistance_vb_ssse. I don't see how this value can end up negative if both of these values are negative.

**Comment by wvangeit** [comment]
Hi,
I look at the script you attached in #114. Indeed you shouldn't pass the absolute value of the stimulus current, but the real value. Your script give the correct input resistance when I remove the abs() around the stimulus current
