### ISSUE TITLE
Add feature "APlast_width"

### ISSUE THREAD

**Issue by elisabettai** [BlueBrain/eFEL#125]
Hi @wvangeit , 
would it be possible to add a new feature for the (time) width of the last spike? I guess it can be similar to AP1_width and AP2_width.

**Comment by wvangeit** [comment]
Sure. It is ok if I implement it in a week or so. Or do you need it more urgently ?

**Comment by elisabettai** [comment]
Thanks. It's not very urgent, in a week is fine for me.

**Comment by wvangeit** [comment]
@elisabettai this was fixed by #126

**Comment by anirban6908** [comment]
@wvangeit If APlast_width is included in feature set the python kernel automatically restarts without throwing an error. Taking out the feature eFEL works normally. 
OS: CentOS 7.5
python 3.6

**Comment by wvangeit** [comment]
is there any chance you could share the trace that causes this ?

**Comment by wvangeit** [comment]
@anirban6908 ok, thanks that trace helped. This should have been solved by https://github.com/BlueBrain/eFEL/pull/159
Let me know if it works now.

**Comment by anirban6908** [comment]
yes..thanks!
