### ISSUE TITLE
Please update package metadata to mention py3 support

### ISSUE THREAD

**Issue by sanjayankur31** [BlueBrain/eFEL#144]
Metadata package files like setup.py only mention py2.7.

Would it also be possible to please include the license and examples in the pypi tar ball?

**Comment by wvangeit** [comment]
I've added the license / author files to the tarbal:
https://github.com/BlueBrain/eFEL/pull/145/files

I've also removed the 2.7 from the metadata

However, I'm reluctant to add the examples to the tarball, since it will add data that is not really useful for the installation of eFEL. Do you have a use case for that ?

**Comment by sanjayankur31** [comment]
Thanks!

Well, the idea is that if a user installs using `pip` or whatever method, they should be able to use the package and the examples help with that. Otherwise, even after one has installed the package, one must go looking for the upstream documentation or repository---an extra step. It isn't a necessity---it just reduces the steps required to use the software in some cases, so if it isn't too much of a maintenance burden, we try to include them.

**Comment by sanjayankur31** [comment]
Just another note: this [builds properly on py3.7 also](https://koji.fedoraproject.org/koji/taskinfo?taskID=31005076). That's the version of Python we're tracking on Fedora "rawhide", so I checked there. We should have eFEL available as part of [NeuroFedora](https://fedoraproject.org/wiki/SIGs/NeuroFedora) in a few days. It is currently under review:

https://pagure.io/neuro-sig/NeuroFedora/issue/116

Thanks again! Please close this ticket when you think it appropriate.

**Comment by wvangeit** [comment]
Ok, I've added tests for py 3.7 to Travis

About the examples, not a big fan if they end up in the site-packages directory. I think it's better people get the examples from github if they need them.
