### ISSUE TITLE
Failure to detect low amp. spikes, fast spiker

### ISSUE THREAD

**Issue by Sverreg** [BlueBrain/eFEL#152]
It appears that eFEL fails to detect low-amplitude spikes in very fast spiking cells (up to 500hz). Changing efel.setDoubleSetting("min_spike_height", 10) has no effect. The detected firing frequency of the traces below are 327, 438 and 302 consecutively. 

Red circles are peak_indices. Attached txt files are sweep data points (time(x), mV(y)).

![Sweep14](https://user-images.githubusercontent.com/27206049/55627715-28fbe180-57af-11e9-8459-ff07f5c249b9.PNG)
![Sweep18](https://user-images.githubusercontent.com/27206049/55627728-2ef1c280-57af-11e9-945b-ab25efe4e3fc.PNG)
![Sweep21](https://user-images.githubusercontent.com/27206049/55627736-31ecb300-57af-11e9-8f53-874ab548f049.PNG)
[Sweep14X.txt](https://github.com/BlueBrain/eFEL/files/3047844/Sweep14X.txt)
[Sweep14Y.txt](https://github.com/BlueBrain/eFEL/files/3047845/Sweep14Y.txt)
[Sweep18X.txt](https://github.com/BlueBrain/eFEL/files/3047846/Sweep18X.txt)
[Sweep18Y.txt](https://github.com/BlueBrain/eFEL/files/3047847/Sweep18Y.txt)
[Sweep21X.txt](https://github.com/BlueBrain/eFEL/files/3047848/Sweep21X.txt)
[Sweep21Y.txt](https://github.com/BlueBrain/eFEL/files/3047849/Sweep21Y.txt)

**Comment by wvangeit** [comment]
An initial question. Which interpolation frequency did you use in eFEL ?
Did you try to increase the frequency ?

**Comment by Sverreg** [comment]
I use an interpolation frequency of 0.01, adjusting it to 0.001 or 0.0001 does not affect spike frequency, adjusting to 0.1 reduces the frequency from 302 to 152 in the bottom sweep (21). 

With 0.1 interp:

![Sweep21_1 0interp](https://user-images.githubusercontent.com/27206049/55628864-1c2cbd00-57b2-11e9-82d9-209d05c5e4fc.PNG)

**Comment by Sverreg** [comment]
Changing the Threshold doublesetting solved this issue, I believed min_spike_height was the only threshold but then I read the docs again.. 

Sweep 22, 484 spikes:
![image](https://user-images.githubusercontent.com/27206049/55731003-ae82ca00-5a19-11e9-9999-9f2510fe24b1.png)

**Comment by wvangeit** [comment]
Ok, np. Good to hear that it works now.
