### ISSUE TITLE
Mistake in documentation for peak indices (2nd) efeature

### ISSUE THREAD

**Issue by seirios** [BlueBrain/eFEL#162]
Hello

I was checking the pseudo-code for peak indices (2nd) in the efeature documentation PDF, and I think there is a mistake.

Where it says:
```
h1 = V[max_i] - min_i
h2 = V[max_i] - min_i+1
```
it should read:
```
h1 = V[max_i] - V[min_i]
h2 = V[max_i] - V[min_i+1]
```
because `min_i` and `min_i+1` are just indices, right?

Also, it lists T in the required trace data, but it's never used in the pseudocode.

Cheers!

**Comment by wvangeit** [comment]
Thanks for pointing that out, I've fixed the pdf.
