### ISSUE TITLE
libstdc++.so.6: undefined symbol: libiconv on gcc.9.2.0

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/eFEL#167]
When I try to import cppcore inside Python while gcc version 9.2.0 is loaded it gives the following error.
 
Importing cppcore: `import efel.cppcore as cppcore`

Error: `PATH_TO_GCC/linux-rhel7-x86_64/gcc-4.8.5/gcc-9.2.0-nz6rnuk53f/lib64/libstdc++.so.6: undefined symbol: libiconv `

It works fine with gcc 8.3.0 or 4.5.0

**Comment by mgeplf** [comment]
What modules and in which order are you loading them?

**Comment by anilbey** [comment]
I only load gcc 9.2.0.

Here are the minimal steps to reproduce it.

1. git clone eFel
2. `module purge`
3. `tox -e py3 -r`
> All tests pass.
4. `module load archive/2020-03; module load gcc/9.2.0`
5. `tox -e py3 -r`
> libstdc++.so.6: undefined symbol: libiconv

**Comment by mgeplf** [comment]
Which python are you using?

**Comment by anilbey** [comment]
Tox is installed as part of this conda env. below [1] but the python that fails the tests is this one [2]. 

1. `/gpfs/bbp.cscs.ch/project/proj37/software/bb5/local-20191205/miniconda/bin/tox`
2. `/gpfs/bbp.cscs.ch/home/tuncel/git-repos/eFEL/.tox/py3/bin/python`

**Comment by mgeplf** [comment]
The `.tox` one is likely generated from the miniconda one.
What does the output of `python-config --libs` look like?

**Comment by anilbey** [comment]
Here it is.
> `-lpthread -ldl -lutil -lm -lpython2.7`

**Comment by mgeplf** [comment]
Ok, my _guess_ about what is happening is that the miniconda python comes w/ its own libraries that don't load libiconv anywhere.

I probably can't help you any more, I would open a ticket on the BSD project.  They'll prob. suggest using their python instead of miniconda, which I think would reduce the interplay of 3 different packaging systems.

**Comment by anilbey** [comment]
I just tried with another tox that is not installed through conda and the error persists.
Now there are 2 packaging systems. 
Here is the tox.
`/gpfs/bbp.cscs.ch/project/proj82/software/bb5/local-20200422181252/pyenv/shims/tox`

**Comment by anilbey** [comment]
This can be closed now. The problem is due to the version of a module we use in our cluster. There already exists a ticket addressing this on the BSD project.
