### ISSUE TITLE
Precision loss in floating point numbers is distorting the feature results

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/eFEL#174]
### Issue summary
The precision loss is falsifying the outcomes of multiple C++ features.
The two values below were supposed to be equal. The comparison (`>`) operator was expected to evaluate false between these two numbers, however it evaluates as true. 
`  ___t[i]:    500.00000000004519052`
`endTime:  500.00000000000000000`

### Example C++ feature (voltage_base)
The voltage_base feature of LibV5 for example is computing a mean value of the vector within a defined start and ending index here:

https://github.com/BlueBrain/eFEL/blob/3b09294ce6b3741ce35c00407cd639a98d469269/efel/cppcore/LibV5.cpp#L2261-L2279

Having tested it multiple times, I can surely say there is nothing wrong in this code's logic.
I also implemented it in Python and tested.

In the test (written in Python) however, the results differ,

https://github.com/BlueBrain/eFEL/blob/3b09294ce6b3741ce35c00407cd639a98d469269/efel/tests/test_basic.py#L905-L909

The original data is a 1 dimensional vector of size 14001. The subvector within the start and end boundaries is of size 501. 
* In Python the mean operation above adds up 501 elements that result in -35844.15544
* In C++ the mean operation above adds up 500 elements that result in -35772.609232

After performing the division in both C++ and Python the results get similar up to the first 5 digits of precision. However that difference is already greater than the difference in using `median` instead of `mean`.

### Why is this happening?

The comparison operation in the line below evaluates true when both operands are equal to 500.000
https://github.com/BlueBrain/eFEL/blob/3b09294ce6b3741ce35c00407cd639a98d469269/efel/cppcore/LibV5.cpp#L2265

They are both literally equal to 500.000
I had to increase the print precision using `std::setprecision` to see the difference.

I noticed this issue while I was implementing the current-base feature with median option here. 
https://github.com/anilbey/eFEL/tree/current-voltage-bases.

There may be similar errors in other features due to precision. The voltage base feature alone is already used by many of the other features.

### How to reproduce?

1. Go to this test file
https://github.com/BlueBrain/eFEL/blob/3b09294ce6b3741ce35c00407cd639a98d469269/efel/tests/test_basic.py#L905-L909
2. Delete the named parameter called `places` or set it to a big value such as 8.
3. There will be an error. A simple mean operation on this test data shouldn't make that amount of difference between different programming languages. You can further debug and look into the sizes of vectors in C++ and Python and you will see that C++ container has one less element than the Python array.

**Comment by anilbey** [comment]
### Update

The precision problem is caused by the LinearInterpolation function in C++.
It has the same behaviour as numpy.arange but with some precision error in computation.
 
https://github.com/BlueBrain/eFEL/blob/3b09294ce6b3741ce35c00407cd639a98d469269/efel/cppcore/Utils.cpp#L28-L32

Fixing it should solve this issue.

**Comment by wvangeit** [comment]
We had a bit of a deeper look into this.
It seems they issue is caused by a slightly different way the time is interpolated between numpy and the C++ efel code.
Since changing that interpolation would affect all the exact feature values, and since it's only a tiny precision difference, I think it's better leave it as it is now.

**Comment by anilbey** [comment]
With the change in #175 we can specify the amount of precision loss to be allowed when it's necessary.
