### ISSUE TITLE
Peak Times Rounding Issue

### ISSUE THREAD

**Issue by alexyonk** [BlueBrain/eFEL#182]
I'm running the EFEL code in an anaconda environment in Ubuntu. I'm in the process of validating select features on an I/V curve. When comparing the EFEL Feature output (peak voltage/times) to the MATLAB findpeaks output, the outputs were not the same. Upon closer inspection, it seems that there is a peak time rounding issue (highlighted in the attached screenshot). EFEL seems to limit the peak time output to one decimal place, even though there is higher precision (20kHz sampling frequency and each sample is 0.05ms). In turn, this changes selected peak voltages, ISI values, etc. 

[validation_data.txt](https://github.com/BlueBrain/eFEL/files/5226856/validation_data.txt)
![peak_times_screenshot](https://user-images.githubusercontent.com/71344986/93248271-a2964e00-f75d-11ea-8d2f-c9cd8b90fb24.png)

**Comment by wvangeit** [comment]
I assume this is caused by the interpolation step that eFEL performs on all traces. You can influence the frequency of this interpolation with:
`efel.setDoubleSetting('interp_step', 0.1)`
(and change the 0.1 to a value you think is appropriate)

**Comment by alexyonk** [comment]
This is exactly what I needed. I assumed there was a parameter, but I wasn't sure where. Thank you!
