### ISSUE TITLE
Error pip installing eFEL on MacOS Catalina

### ISSUE THREAD

**Issue by joewgraham** [BlueBrain/eFEL#184]
[efel_install.txt](https://github.com/BlueBrain/eFEL/files/5599440/efel_install.txt)

See the attached file for the output from an attempted 'pip3 install efel'
Mac OS X, 10.15.7
Python 3.8.2

**Comment by wvangeit** [comment]
Hi @joewgraham

Are you sure you're on Catalina? The weird thing is that your install log contains e.g.:
creating build/lib.macosx-10.14.6-x86_64-3.8

10.14 is MacOS Mojave. Maybe you would need to update XCode? (or your python that is in /Users/graham/temp/env/bin/python3)

I'm running Catalina atm, and didn't have a problem installing the package.

**Comment by wvangeit** [comment]
@joewgraham 
Was this solved in the end?

**Comment by joewgraham** [comment]
I ran into the error while reviewing an article, and never heard back about the review, so never looked into it again.  I just tried `python3 -m pip install efel` and it worked perfectly.
