### ISSUE TITLE
Ability to change AP rise time parameters

### ISSUE THREAD

**Issue by alexyonk** [BlueBrain/eFEL#194]
I've looked through the documentation and I haven't found what I'm looking for specifically. I'm trying to change the rise time window from 0-100% (time difference between AP_begin_index to peak_index) to 10-90%. Is this a possibility with this algorithm?

**Comment by wvangeit** [comment]
At the moment this feature is implemented as the difference between the time of the peak and the start of the spike (using the respective features to calculate these):
```
aprisetime[i] = t[peakindices[i]] - t[apbeginindices[i]]
```
With the 10-90% do you mean the voltage is at 10-90% of the AP amplitude?

**Comment by alexyonk** [comment]
For example, say that the AP_begin_voltage occurs at 0mV and the peak_voltage is 100mV. Instead of calculating the full rise time (0 - 100), is there a way to **calculate the time it takes to rise** from 10% to 90% of the voltage?

**Comment by wvangeit** [comment]
Unfortunately I don't think we have a feature that can be used for that. It could be implemented, I only wonder how we should parametrize it. I assume we don't want to fix the 10%-90% levels

**Comment by alexyonk** [comment]
I would agree with the last statement. According to a more experienced colleague, the calculations relating to rise time are variable (10-90%, 20-80%, etc.). Would it be possible to include both rise_begin_perc and rise_end_perc as global settings that can be modified by the user similar to interp_step and voltage_base_start_perc?

**Comment by wvangeit** [comment]
@AurelienJaquier or @anilbey  Could you have a look at adding this to the feature? The default should be the old behavior. Thanks.

**Comment by AurelienJaquier** [comment]
This issue should have been solved with PR #198
