### ISSUE TITLE
module 'efel.cppcore' has no attribute 'initialize'  

### ISSUE THREAD

**Issue by mik-schutte** [BlueBrain/eFEL#199]
Hi,

I'm using a package that is dependent on the eFEL module. When importing eFEL I get the following error:
Code that caused the error: `from efel import *`

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from efel import *
  File "C:\Users\miksc\anaconda3\envs\CompNeuro\lib\site-packages\efel\__init__.py", line 23, in <module>
    from efel.api import *
  File "C:\Users\miksc\anaconda3\envs\CompNeuro\lib\site-packages\efel\api.py", line 546, in <module>
    reset()
  File "C:\Users\miksc\anaconda3\envs\CompNeuro\lib\site-packages\efel\api.py", line 97, in reset
    _initialise()
  File "C:\Users\miksc\anaconda3\envs\CompNeuro\lib\site-packages\efel\api.py", line 343, in _initialise
    cppcore.Initialize(_settings.dependencyfile_path, "log")
AttributeError: module 'efel.cppcore' has no attribute 'Initialize'

Installed packages in my environment are:
[requirements.txt](https://github.com/BlueBrain/eFEL/files/5965240/requirements.txt)

What's going wrong that the attribute cannot be found. I am pretty new to this so if you need any additional information let me know. Also, is this the correct place to post questions like this?

**Comment by wvangeit** [comment]
It's a bit difficult for us to debug since we don't have access to Windows machines. My guess would be that the efel.cppcore package is not installed, or not correctly. Do you have a compiler installed on your machine? This package is written in C++ so it needs a compiler for its installation.

**Comment by mik-schutte** [comment]
I am using the [cython](https://cython.readthedocs.io/en/latest/src/quickstart/overview.html) compiler; version = 0.29.21. As for the efel.cppcore package this does appear to be installed in the right environment.

**Comment by mik-schutte** [comment]
Alright, I believe the problem was with the dependent package instead of the eFel module. The simple fix of reinstalling didn't work at first due to conda installs. However, using pip did work and has managed to rid me of this error.
Thanks for thinking with me though.

**Comment by wvangeit** [comment]
👍 FYI, we're also working on getting our continuous integration tests working on Windows servers.
