### ISSUE TITLE
Feature request, peak riserate/fallrate

### ISSUE THREAD

**Issue by Sverreg** [BlueBrain/eFEL#200]
Hi,

Would it be possible to add a new feature that outputs the peak rise rate and fall rate? Or upstroke/downstroke as described in [Allen's ephys whitepaper](http://help.brain-map.org/display/celltypes/Documentation):

![image](https://user-images.githubusercontent.com/27206049/107780159-9d5a2100-6d46-11eb-929e-e66ee61f1c49.png)

**Comment by wvangeit** [comment]
@AurelienJaquier do you mind having a look at this? I think it's best to implement it as a pure python feature.

**Comment by Sverreg** [comment]
Thank you @wvangeit and @AurelienJaquier for implementing this so quickly. Tested on my data today with eFEL 3.1.82 and it works as expected.

**Comment by wvangeit** [comment]
👍
