### ISSUE TITLE
AHP search timing parameter

### ISSUE THREAD

**Issue by Sverreg** [BlueBrain/eFEL#201]
Currently the search window for slow after-hyperpolarization features cannot be defined by parameters, and is set to start at 5 ms after peak. For fast firing cells this timing can be too slow. The issue could be avoided by declaring the start of the slow AHP search window in a parameter, ie. `sahp_start = 5`. 

The current default window is `5 ms after peak --> next peak`. The features are `AHP_depth_abs_slow` and `AHP_slow_time`.

Additionally, the fast after-hyperpolarization window could be defined as `peak --> sahp_start`.

**Comment by wvangeit** [comment]
@AurelienJaquier, if you could also have a look at this. Thx.

**Comment by Sverreg** [comment]
Works as expected with eFEL 3.1.82. Thanks again for the rapid implementation!

**Comment by wvangeit** [comment]
👍
