### ISSUE TITLE
Direct links to features in documentation

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/eFEL#209]
I'm not sure why, but it seems some features in the readthedocs documentation can be linked to directly (have a double ring symbol next to them), and others don't (mostly the features at the top of the document)
I mean this kind of link:
https://efel.readthedocs.io/en/latest/eFeatures.html#libv1-steady-state-voltage
We should make sure all features get a direct link, so it can be used in other documentation

@AurelienJaquier could you maybe have a look? Thx.

**Comment by AurelienJaquier** [comment]
Sure, I'll have a look at it.

**Comment by AurelienJaquier** [comment]
Issue solved with https://github.com/BlueBrain/eFEL/pull/210
