### ISSUE TITLE
irregularity_index

### ISSUE THREAD

**Issue by shirquinn** [BlueBrain/eFEL#226]
Hi all
I couldn't find information of the irregularity_index feature, can someone explain what it is and how it is calculated?

**Comment by DrTaDa** [comment]
Hi @shirquinn, 

It computes the mean of the differences between subsequent ISIs.
(https://github.com/BlueBrain/eFEL/blob/d252fccb20bfa87ef6614f7a5e16506f4e69c4a7/efel/cppcore/LibV5.cpp#L822).

Another feature that might interest you is ISI_CV.

**Comment by shirquinn** [comment]
Thanks

**Comment by wvangeit** [comment]
@AurelienJaquier could you check if this feature is mentioned in the doc? Otherwise it might be worthwhile to add a description. Thx.
