### ISSUE TITLE
Problem with Spikecount if first value in voltage trace is positive

### ISSUE THREAD

**Issue by appukuttan-shailesh** [BlueBrain/eFEL#240]
I was trying to evaluate features such as `Spikecount` from my data file, but kept getting "zero" spikes even though the data contains several spikes. Parameters such as `maximum_voltage` and `minimum_voltage` were being evaluated correctly.

After quite a bit of experimenting, it seems that if the voltage trace starts from a depolarized level (e.g. +2 mV in my case) the Spikecount (and some other Spike Event features) do not seem to work as (I?) expected. When I changed just the first V value to near RMP (-65 mV), the eFEL extraction worked perfectly. So is this a known requirement for the voltage trace? I hadn't noticed it documented, and was also wondering the reason for such a constraint (if by design)

sample data attached (data.xlsx)
[data.xlsx](https://github.com/BlueBrain/eFEL/files/9372507/data.xlsx)

_(had posted on eFEL gitter channel, but wasn't sure if it is still actively monitored, so re-posting here)_

**Comment by wvangeit** [comment]
Afaik the spikes are detected as: a part of the trace that starts below the spike threshold then crosses it, goes down again, and crosses it again. Maybe the depolarized level messes with this definition. @AurelienJaquier or @anilbey can you have a look? Thx

**Comment by AurelienJaquier** [comment]
Hi @appukuttan-shailesh thanks for raising this issue, this has been solved in the latest efel version.
If you use `spikecount` with a trace that starts above the threshold, efel will count all spikes **after** the trace has gone below threshold. So be aware that the first 'incomplete' spike is ignored.

**Comment by appukuttan-shailesh** [comment]
Thanks a lot for the fix @AurelienJaquier , @wvangeit !
Losing the first incomplete spike is very reasonable. I shall close this ticket.
