### ISSUE TITLE
Possible (mini) error in documentation for inv_first_ISI

### ISSUE THREAD

**Issue by appukuttan-shailesh** [BlueBrain/eFEL#243]
The docs for `inv_first_ISI` here:
https://efel.readthedocs.io/en/latest/eFeatures.html#libv5-all-isi-values-inv-first-isi-inv-second-isi-inv-third-isi-inv-fourth-isi-inv-fifth-isi-inv-last-isi

gives two slightly different pseudo codes for this parameter:
```
if len(all_isi_values_vec) > 1:
    inv_first_ISI = 1000.0 / all_isi_values_vec[0]
else:
    inv_first_ISI = 0

if len(all_isi_values_vec) > 0:
    inv_first_ISI = 1000.0 / all_isi_values_vec[0]
else:
    inv_first_ISI = 0
```

I suppose the first part (>1) is unnecessary, and the second (>0) is what is used.

**Comment by wvangeit** [comment]
Thx, @AurelienJaquier 's PR above should have fixed this issue.
