### ISSUE TITLE
Update Readthedocs python interpreter to python 3.X

### ISSUE THREAD

**Issue by AurelienJaquier** [BlueBrain/eFEL#245]
Pyhton2.7 support for efel was dropped some time ago, but readthedocs is still using it and thus fails to build efel's docs. @wvangeit could you change this in the readthedocs settings please?

**Comment by wvangeit** [comment]
@AurelienJaquier , I think it's working now.
Two questions:
- Can you update the copyright year in the main page of the readthedocs doc
- Could you make a readthedocs config file in the efel repo. I have attached the current config.

![Screenshot 2022-08-26 at 10 53 58](https://user-images.githubusercontent.com/3098670/186868733-62f315ba-7630-42fc-8de8-b30378e5227f.png)

**Comment by wvangeit** [comment]
Thx @AurelienJaquier
