### ISSUE TITLE
Recommended method for citing eFEL

### ISSUE THREAD

**Issue by appukuttan-shailesh** [BlueBrain/eFEL#251]
Is there a recommended method to cite eFEL in articles? It would be nice to include this in the README or docs.
I checked through a few publications, and find the following:
>Blue Brain Project (2015). eFEL. Available online at: https://github.com/BlueBrain/eFEL (Accessed February 16, 2016).
or
>BlueBrain. BlueBrain/eFEL [Internet]. 2018. Available from: https://github.com/BlueBrain/eFEL

Based on this, we could develop a bibtex reference something like:
```
@misc{eFELgithub,
  author = {Blue Brain Project},
  title = {BlueBrain/eFEL},
  howpublished = "\url{https://github.com/BlueBrain/eFEL}",
  year = {2015}, 
  note = "[Online; accessed 31-August-2022]"
}
```

**Comment by anilbey** [comment]
Hi @appukuttan-shailesh thanks for the issue.

I recall there was a recent GitHub feature for citing the code.

Tweet by Nat Friedman,  introducing the citation feature
https://twitter.com/natfriedman/status/1420122675813441540

**Comment by anilbey** [comment]
More info:
https://blog.front-matter.io/posts/step-forward-for-software-citation/
https://github.blog/2021-08-19-enhanced-support-citations-github/

**Comment by mgeplf** [comment]
We have information on this:
https://bbpteam.epfl.ch/project/spaces/pages/viewpage.action?pageId=89589507

**Comment by mgeplf** [comment]
(should add that I think @alex4200 is always looking to improve the process, so if there are new features that should be included, I'm sure he'd love to know)

**Comment by wvangeit** [comment]
@appukuttan-shailesh I would propose you keep on using the citation as you originally described.

At some point Zenodo (https://zenodo.org/record/1283474) might be better, but it seems at the moment there are all kinds of things wrong with the Zenodo website. I'm getting internal server errors etc. 

We're also about to publish a paper describing a bit our workflow, in the future it would be better to cite that paper.

**Comment by appukuttan-shailesh** [comment]
Sure @wvangeit . Will do that. Thanks.
