### ISSUE TITLE
Wrong AP_begin

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/eFEL#279]
@AurelienJaquier  In the trace below I plot the first values AP_begin_voltage and AP_begin_time with thin black lines:
[trace_('C070109A4-C1', 'IDRest_150_0').pdf](https://github.com/BlueBrain/eFEL/files/11061007/trace_.C070109A4-C1.IDRest_150_0.pdf)

which are obviously not at the correct place. I'm not sure what would be a good fix for such cases.

Here is data of this trace:
[trace.csv](https://github.com/BlueBrain/eFEL/files/11061019/trace.csv)

**Comment by AurelienJaquier** [comment]
I'll have a look once I'm back.
Since depol_block depends on AP_begin_voltage, a bad AP_begin_voltage could explain a depol_block trigger.

**Comment by AurelienJaquier** [comment]
Yeah. Here is when AP_begin is detected: 

> Spike start is defined as where the first derivative of the voltage trace is higher than 10 V/s , for at least 5 points

So AP_begin_voltage is behaving as expected. I guess we didn't expect this kind of traces when the feature was created. Not sure either how to fix this.

**Comment by arnaudon** [comment]
Maybe we could add an if > voltage_base ?

**Comment by wvangeit** [comment]
That looks like a hack we might regret later

**Comment by arnaudon** [comment]
So what could be a better fix? One could have another hack to delay the ton for this feature by a few ms. This little weird thing at start of step appears in quite  a lot of traces, but if often not strong enough to trigger AP_begin

**Comment by AurelienJaquier** [comment]
I'll mark this as solved by PR https://github.com/BlueBrain/eFEL/pull/287
