### ISSUE TITLE
postburst_min_values (and interburst_min_values) - don't work as expected - fast AHP after last spike in burst reported instead of slow AHP.

### ISSUE THREAD

**Issue by PolinaL** [BlueBrain/eFEL#282]
Both _postburst_min_values_ and __interburst_min_values_ seem to measure the fast AHP right after last spike, and not the slow AHP between bursts, as expected. 
Please see attached trace (model in purple, experimental data in color) - _postburst_min_values_ exp. data extracted value is "mean": -78.15430187470984, "original_std": 2.88731485936629, model value is  -78.60786914391257.
![RTN_EI_params_64339_ZOOMEDCell#2_Jul_9_Step_ReboundBurstProtocol_burst_-300](https://user-images.githubusercontent.com/9979668/228259573-293f2c42-d612-4532-bc0c-7d51cb6d8f7c.png)
Thanks.

**Comment by PolinaL** [comment]
time and voltage data for both model and experimental traces [time_and_voltage.zip](https://github.com/BlueBrain/eFEL/files/11090471/time_and_voltage.zip)

**Comment by arnaudon** [comment]
Here is a zoom, they apper on top of each other, but the red one should be at around -60 instead of at the fast AHP: ![zoom](https://user-images.githubusercontent.com/12429955/228273311-818724b6-ed92-4b27-9600-63d52b6f95d3.png)

**Comment by arnaudon** [comment]
I suppose it should be a shift around here: https://github.com/BlueBrain/eFEL/blob/master/efel/cppcore/LibV5.cpp#L3881 but I don't understand cpp and this code enough to try to do it unfortunately...

**Comment by arnaudon** [comment]
@PolinaL , try this: https://github.com/BlueBrain/eFEL/pull/283 , it solves it for the trace you shared: 
![zoom](https://user-images.githubusercontent.com/12429955/229055800-a137c9ca-5152-4ec8-9308-590228b5533e.png)

**Comment by AurelienJaquier** [comment]
Hi @PolinaL !
Did the new features in PR #289  solve your problem?
If so, I will merge the PR and close this issue

**Comment by AurelienJaquier** [comment]
I'll close this issue since the related PR has been merged

**Comment by AurelienJaquier** [comment]
I'll also close the postburst-slow-ahp branch. You can use the master branch now, it contains all the post-burst features
