### ISSUE TITLE
Creating a new feature for decay_time_constant_multiple_steps

### ISSUE THREAD

**Issue by darshanmandge** [BlueBrain/eFEL#284]
Hi,
For traces where we have multiple step injections e.g. SpikeRec, I need to calculate decay time constant of membrane potential after step injection for each step input in a trace and get the mean value of all time constants for all steps in the trace. 

Since, there are multiple steps in SpikeRec, decay_time_constant_after_stim feature does not work as we need to specify stim_start and stim_end.

Can a new feature be created e.g decay_time_constant_multiple_steps for get time constant for multiple steps?

Thanks,
Darshan

**Comment by DrTaDa** [comment]
I propose for the feature to be called multiple_decay_time_constant.

I do not see how to get it to work without having the user/BluePyEfe inform the begin and end of every steps (as there is no step detection in eFEL).
Therefore, there is a need for new settings:
multi_stim_start (list)
multi_stim_end (list)

Then, the new feature can run time_constant_stim_end for each stim_start and stim_end and return a list of time constant.
