### ISSUE TITLE
Python wheel distribution?

### ISSUE THREAD

**Issue by theowoo** [BlueBrain/eFEL#33]

**Comment by wvangeit** [comment]
Hi,
For which operating system / python version would you like to have a wheel ?

**Comment by theowoo** [comment]
Current system: Windows 8.1 64-bit, Python 2.7.10
But in general win_amd64, thanks.

**Comment by wvangeit** [comment]
Ok, will have a look at it, but it looks like Travis (the service that pushes the packages to PyPi doesn't support Windows atm)
https://github.com/travis-ci/travis-ci/issues/216

**Comment by wvangeit** [comment]
It seems we don't have access to a Windows machine that could creates these wheels. 
I would suggest you install:
http://www.microsoft.com/en-us/download/details.aspx?id=44266
That way your OS should be able to compile the C++ extension.

We're not planning to support binary wheels in the near future, so I will close this ticket.
