### ISSUE TITLE
Can't install efel on macos sonoma

### ISSUE THREAD

**Issue by deleiva** [BlueBrain/eFEL#332]
Hello
I am running in problems trying to install efel in macos sonoma m1, it gave me an error and it did not install
 % pip install efel
Collecting efel
  Using cached efel-5.2.8.tar.gz (106 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.6 in ./anaconda3/lib/python3.11/site-packages (from efel) (1.24.3)
Building wheels for collected packages: efel
  Building wheel for efel (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for efel (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      Failed to load config from /private/var/folders/5j/v0vq38ls38g75sr6_2b6t0sr0000gn/T/pip-install-n6u5myv5/efel_4290456a89164bc2ba83e911c436a9ed/pyproject.toml: 'versioneer'
      Try to load it from setup.cfg
      running bdist_wheel
      running build
      running build_py
      Failed to load config from /private/var/folders/5j/v0vq38ls38g75sr6_2b6t0sr0000gn/T/pip-install-n6u5myv5/efel_4290456a89164bc2ba83e911c436a9ed/pyproject.toml: 'versioneer'
      Try to load it from setup.cfg
      Failed to load config from /private/var/folders/5j/v0vq38ls38g75sr6_2b6t0sr0000gn/T/pip-install-n6u5myv5/efel_4290456a89164bc2ba83e911c436a9ed/pyproject.toml: 'versioneer'
      Try to load it from setup.cfg
      creating build
      creating build/lib.macosx-11.1-arm64-cpython-311
      creating build/lib.macosx-11.1-arm64-cpython-311/efel
      copying efel/_version.py -> build/lib.macosx-11.1-arm64-cpython-311/efel
      copying efel/io.py -> build/lib.macosx-11.1-arm64-cpython-311/efel
      copying efel/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/efel
      copying efel/api.py -> build/lib.macosx-11.1-arm64-cpython-311/efel
      copying efel/settings.py -> build/lib.macosx-11.1-arm64-cpython-311/efel
      creating build/lib.macosx-11.1-arm64-cpython-311/efel/pyfeatures
      copying efel/pyfeatures/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/efel/pyfeatures
      copying efel/pyfeatures/pyfeatures.py -> build/lib.macosx-11.1-arm64-cpython-311/efel/pyfeatures
      creating build/lib.macosx-11.1-arm64-cpython-311/efel/units
      copying efel/units/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/efel/units
      copying efel/DependencyV5.txt -> build/lib.macosx-11.1-arm64-cpython-311/efel
      copying efel/units/units.json -> build/lib.macosx-11.1-arm64-cpython-311/efel/units
      creating build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/Utils.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/LibV1.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/LibV2.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/LibV3.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/LibV5.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/FillFptrTable.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/DependencyTree.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/efel.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/cfeature.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/Global.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/mapoperations.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/types.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      copying efel/cppcore/eFELLogger.h -> build/lib.macosx-11.1-arm64-cpython-311/efel/cppcore
      UPDATING build/lib.macosx-11.1-arm64-cpython-311/efel/_version.py
      set build/lib.macosx-11.1-arm64-cpython-311/efel/_version.py to '5.2.8'
      running build_ext
      Failed to load config from /private/var/folders/5j/v0vq38ls38g75sr6_2b6t0sr0000gn/T/pip-install-n6u5myv5/efel_4290456a89164bc2ba83e911c436a9ed/pyproject.toml: 'versioneer'
      Try to load it from setup.cfg
      Failed to load config from /private/var/folders/5j/v0vq38ls38g75sr6_2b6t0sr0000gn/T/pip-install-n6u5myv5/efel_4290456a89164bc2ba83e911c436a9ed/pyproject.toml: 'versioneer'
      Try to load it from setup.cfg
      building 'efel.cppcore' extension
      creating build/temp.macosx-11.1-arm64-cpython-311
      creating build/temp.macosx-11.1-arm64-cpython-311/efel
      creating build/temp.macosx-11.1-arm64-cpython-311/efel/cppcore
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/elias/anaconda3/include -arch arm64 -fPIC -O2 -isystem /Users/elias/anaconda3/include -arch arm64 -Iefel/cppcore/ -I/Users/elias/anaconda3/include/python3.11 -c efel/cppcore/DependencyTree.cpp -o build/temp.macosx-11.1-arm64-cpython-311/efel/cppcore/DependencyTree.o -std=c++17
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/elias/anaconda3/include -arch arm64 -fPIC -O2 -isystem /Users/elias/anaconda3/include -arch arm64 -Iefel/cppcore/ -I/Users/elias/anaconda3/include/python3.11 -c efel/cppcore/FillFptrTable.cpp -o build/temp.macosx-11.1-arm64-cpython-311/efel/cppcore/FillFptrTable.o -std=c++17
      In file included from efel/cppcore/FillFptrTable.cpp:18:
      In file included from efel/cppcore/FillFptrTable.h:24:
      In file included from efel/cppcore/LibV1.h:23:
      efel/cppcore/Utils.h:31:10: fatal error: 'EfelExceptions.h' file not found
      #include "EfelExceptions.h"
               ^~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for efel
Failed to build efel
ERROR: Could not build wheels for efel, which is required to install pyproject.toml-based projects

I really have no idea what to do :(

**Comment by AurelienJaquier** [comment]
@deleiva thanks for reporting this issue. We fixed the bug, you should be able to install efel now.

**Comment by deleiva** [comment]
Thanks, it works
----------------------------------------

Nov 22, 2023 06:41:44 Aurélien Jaquier ***@***.***>:

**Comment by AurelienJaquier** [comment]
Great! Then I'll close this issue.
