### ISSUE TITLE
Hyperlinking features in the docs

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/eFEL#337]
Could we also add a page in documentation with index of all the features hyperlinking each to the description in the documentation? This would help scientists to search for features and glance through all the features at once :) . It could also be done in a separate PR.

_Originally posted by @darshanmandge in https://github.com/BlueBrain/eFEL/pull/334#pullrequestreview-1781831268_

**Comment by AurelienJaquier** [comment]
Should we consider this to be done, now that we have the table of content on the right side of the page, thanks to switching to the blue brain sphinx theme?

**Comment by darshanmandge** [comment]
Yes, thanks!

**Comment by AurelienJaquier** [comment]
Great, then I'll close the issue (and take all the credit hehehe)
