### ISSUE TITLE
Failed building on Windows

### ISSUE THREAD

**Issue by Chris-crisur** [BlueBrain/eFEL#63]
It seems running the `pip install efel` command on Windows (10) fails for both python 2.7.11 using standalone Visual C++ Compiler for Python 2.7 (Visual C++ 9.0) installed as well as python 3.5.1 using Visual Studio 14.0

Here is the log file when trying to build for python 3.5.1
[pip install efel output.txt](https://github.com/BlueBrain/eFEL/files/335037/pip.install.efel.output.txt)

**Comment by mgeplf** [comment]
Thanks for the report.

I believe that I have a diff to fix this, but I need to test it against Windows again.  I will try to do so tonight.

**Comment by wvangeit** [comment]
As mentioned by @mgeplf, we might have a patch to solve this.
However, we would like to mention we're not officially supporting the Windows platform for the moment.

**Comment by mgeplf** [comment]
Unfortunately, the patch I was thinking of solved a different problem.

I don't regularly have access to a windows machine, so it's hard to make and test a fix.  I will see what I can do about that, but I wouldn't expect anything in the next couple days.

**Comment by mgeplf** [comment]
I have taken the commits that I think are necessary for windows compilation, and put them in the https://github.com/BlueBrain/eFEL/tree/windows_build branch.

With a recent pip, could you try:
```pip install git+https://github.com/BlueBrain/eFEL@windows_build```

**Comment by wvangeit** [comment]
@Chris-crisur, I have merged the changes made by @mgeplf into the master branch. These changes were also pushed to pypi. So could you test if 'pip install efel --upgrade' works for you now ? 
Thanks.

**Comment by Chris-crisur** [comment]
Thanks @mgeplf and @wvangeit 
The changes worked for python 2.7, but not so successful for python 3.5
I'm happy with it working for python 2.7, but thought you'd like to know regarding python 3.5
[pip install efel output2.txt](https://github.com/BlueBrain/eFEL/files/336689/pip.install.efel.output2.txt)

**Comment by mgeplf** [comment]
Glad we've made progress on 2.7.

Could you try this branch for the newer version of VS:
https://github.com/BlueBrain/eFEL/tree/fix_bind2nd_include

**Comment by Chris-crisur** [comment]
'pip install git+https://github.com/BlueBrain/eFEL@fix_bind2nd_include' works on python 3.5 (VS 14.0)!

**Comment by mgeplf** [comment]
Excellent, thanks for the help.

**Comment by wvangeit** [comment]
@Chris-crisur Ok, great to see it works. Thanks for the help. Changes have been pushed in the master, closing this issue
