### ISSUE TITLE
Spikecount cannot be estimated when signal at the end of the trace is larger than the threshold

### ISSUE THREAD

**Issue by croessert** [BlueBrain/eFEL#71]
This was reported by @sasaray.

First trace gives Spikecount 3 while second trace returns Spikecount 0.
When the signal at the end of the trace is larger than the threshold, Spikecount and possibly other features cannot be estimated. This seems to be independent of stim_end.

![figure_1](https://cloud.githubusercontent.com/assets/5420759/17175365/75b79702-5407-11e6-9053-94b126236b21.png)

```
import numpy
import matplotlib
import matplotlib.pyplot as plt
import efel

dt = 0.1
v = numpy.zeros(int(100/dt)) - 70.0
v[int(20/dt):int(25/dt)] = 20.
v[int(40/dt):int(45/dt)] = 20.
v[int(60/dt):int(65/dt)] = 20.

traces = []
trace = {}
trace['T'] = numpy.arange(len(v))*dt
trace['V'] = v
trace['stim_start'] = [10]
trace['stim_end'] = [50]
traces.append(trace)

plt.subplot(2,1,1)
plt.plot(trace['T'], trace['V'])

traces_results = efel.getFeatureValues(traces,['Spikecount'])
print traces_results

# When the signal at the end of the trace is larger than the threshold, Spikecount and possibly other features cannont be estimated.
v[int(80/dt):] = -19

traces_results = efel.getFeatureValues(traces,['Spikecount'])
print traces_results

plt.subplot(2,1,2)
plt.plot(trace['T'], trace['V'])
plt.show()
```

**Comment by wvangeit** [comment]
Ok, strange, will have a look at it.

**Comment by wvangeit** [comment]
Mmm, it looks like this was kind of 'expected' behavior in the feature peak_indices. There is an error: "Voltage never goes below threshold after last spike."
Don't really agree with this behavior. Maybe I can make a LibV5 peak_indices feature that doesn't have it ...

**Comment by wvangeit** [comment]
@croessert PR #95 should have fixed this (I added a test based on your script)
