### ISSUE TITLE
Spikes are counted outside the stimulus

### ISSUE THREAD

**Issue by christian-oreilly** [BlueBrain/eFEL#76]
Not sure if this should be reported as a bug or as a request for enhancement, depending on whether the behavior I'm reporting is intended or not. I used a snippet of code inspired from the GitHub main page:
```
        trace = {}
	trace['T'] = copy(t_vec)
	trace['V'] = copy(v_vec)
	trace['stim_start'] = [h.stim.delay]
	trace['stim_end'] = [h.stim.delay + h.stim.dur]
	traces.append(trace)
	traces_results = efel.getFeatureValues(traces, ['Spikecount'])
```
and it took me quite a while to realize that Spikecount (an many other features I guess) is actually not taken into account the stim_start and stim_end and will include in its count any spikes in the trace, regardless of the stimulus window. Is that intended? If not, it should definitely be corrected. If yes, I would suggest adding some boolean parameter allowing the users to specify if they want the features to be computed on the full trace or on the stimulus window only.

**Comment by wvangeit** [comment]
Yes, this was originally intended like this.
The original traces the eFEL was used for (eCode), were considered 'wrong' anyway when there were spikes outside of the interval.
We could maybe add a new feature that only counts spike inside the stimulus interval interval.

**Comment by christian-oreilly** [comment]
A more general approach using a supplementary boolean argument stating if the user wants to restrict the computation to the stimulus interval with a default value to False (so that it does not break any existing code using eFel) might be desirable to the extent that this issue shows up in various features and duplicating all of them seem not desirable. 

I tend to consider the pre-stimulus period useful to let the transient dies out. If I'm exploring a space of possible modelling parameter values which contains some solutions that raise the equilibrium potential of my modelled cell, the transient from the initial membrane potential to the equilibrium can in some part of my parameter space create an initial spike which enters in the count. So, although my model stays completely flat line in response to the stimulus, the use of eFel lead me to believe that I am in a part of the parameter space in which my modelled cell is responsive, unless I eyeball every solution trace (which I might not do if I'm in a "pattern analysis and machine learning" kind of application). Importantly, it also affects many other features such as the between spike intervals (e.g., create a spurious 1s interval between between the spike due to transients and the beginning of the stimulus-related spiking from my stimulus in the [1, 2]s window). I had issues like this. I think @elisabettai also got spurious feature values related to similar issues. I guess may not be alone. Arguably, the user can add some code that ensure that the transients dies out before the actual simulation (or just cut the first 100 ms or so from the traces they pass to eFel), but this might not solve the issue when dealing with cells that can spontaneously fires some action potential at resting state (or at least, in the pre-stimulus window). As a general case, I would think this behaviour might not be intrinsically wrong. I could also imagine easily a case where I have spontaneous tonic firing, which frequency is modified by a stimulus step current and I want to extract this modified frequency. Aren't these use cases making sense? 

At the very lease, if you don't think it is desirable to add such a binary optional argument, I guess it would be a good idea to raise a warning when spikes from outside the stimulus period are detected and used in the computation of the features. The user can always disable such warning through standard python warning management code if they are annoyed by them in a case where spiking outside the stimulus interval is normal...

**Comment by wvangeit** [comment]
Well, I'm not saying it's a bad idea. But the C++ API doesn't allow for such options to eFeatures at the moment. So if we want to add that, it means changing the entire API, which will take time.

Another option would be that I add a variable you can set inside the eFEL, that changes the behaviour of all features at the same time. However, this requires the C++ code of every feature that's affected by this, to be changed so that it takes into account this variable. Which again will take quite some time.

Do you have a list of specific features you need to have this option ? Many features already work only inside the stimulus interval anyway.
I think it would still make sense to just add new features, like e.g. SpikeCount_stimint, for the features that measure outside of the interval.

**Comment by elisabettai** [comment]
It seems that easiest solution would be to add a new feature similar to Spikecount, but which counts only spikes within the stimulus interval. It you should be the last option you @wvangeit suggested.

**Comment by christian-oreilly** [comment]
(sorry for not following on this earlier; thanks @elisabettai for bringing
it back) I guess, there are two levels of thinking on that: (1) good API
architecture/usability (for the holy quest of the perfect software) vs. (2)
efficient use of BBP resources (in this case, Werner's time! ). So, in the
end, considering that, I'm also fine with your proposal (already supported
by Elisabetta) of adding SpikeCount_stimint. Also, in spirit of (2), I
personally have no immediate need for other *_stimint  features that I
cannot easily compute from SpikeCount_stimint (such as spiking frequency).

2017-01-09 10:34 GMT+01:00 elisabettai <notifications@github.com>:

**Comment by wvangeit** [comment]
@elisabettai @christian-oreilly, ok, so in the mean time I will add the SpikeCount_stimint feature

**Comment by wvangeit** [comment]
Fixed by #81 
The feature Spikecount_stimint was added

**Comment by wvangeit** [comment]
@christian-oreilly @elisabettai @croessert #91 (merged) is a first towards making efeatures only calculate within the stimulus interval. There is now a setting called 'strict_stiminterval', which is set to False by default (for backward compatibility). You can change this setting by calling efel.setIntSetting("strict_stiminterval", strict). When True, the feature peak_indices will only returns the spikes inside the stimulus interval (and all the features that depend on this, like Spikecount, peak_time). 
I want to stress this is only a first step. Features like AHP_depth will now only look at spikes inside the interval, but if the AHP itself falls outside of the interval, it will still be reported. I will need to manually change these kind of other features too. Please create another ticket if you want specific features to be fixed.
I will also change BluePyOpt to allow you to specifiy the strict_stiminterval.

**Comment by wvangeit** [comment]
@a1eko you might also be interested in this
