### ISSUE TITLE
ambiguous burst number and wrong location

### ISSUE THREAD

**Issue by romani79** [BlueBrain/eFEL#90]
I have a couple of possible related issues.
1) The burst_number can be 1 even if there are no burst in the traces.
Than, how should I interpret the burst_number = 1? 1 or 2 bursts?
2) burst_ISI_indices seems not to work properly. In one of the traces I am working on, I expect 1 or 2 bursts occur at the very beginning on the trace, but I obtained burst_ISI_indices = 5.

**Comment by wvangeit** [comment]
Attaching trace for reference 
[data.txt](https://github.com/BlueBrain/eFEL/files/732206/data.txt)

**Comment by wvangeit** [comment]
@romani79, so I checked the trace. This trace shows '2' bursts (burst_number). Seems to make sense to me. If burst_number is 1 the trace consists of continuous spikes. It's a discussion about semantics, but to me that makes sense. 
Regarding the burst_ISI_indices, as makes sense to me. So the ISI with index 5 (starts counting at 0), looks to me like the ISI that splits the two 'bursts'.
