### ISSUE TITLE
Interpolate for all features

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/eFEL#98]
E.g. voltage_base doesn't trigger the interpolation of the trace.
Ideally interpolation of the trace should be triggered for all the features

**Comment by elisabettai** [comment]
It may be related, but I think that I have some errors in the computation of the features "voltage_deflection" and "voltage_deflection_begin". For example in this trace:
![iv_trace](https://cloud.githubusercontent.com/assets/18575092/25243597/d9f828a8-25fd-11e7-8bf6-85d40d1c2d05.png)
 I have:
_.IV_-140.soma.v.voltage_deflection: -14.073131634882756
_.IV_-140.soma.v.voltage_deflection_begin: -17.271396780376847

**Comment by wvangeit** [comment]
Could you share the raw trace ? Thx

**Comment by elisabettai** [comment]
Sure. 
[IV_trace.txt](https://github.com/BlueBrain/eFEL/files/946609/IV_trace.txt)

I've also plotted the single points of the trace. They seem really few in some parts, but I guess it's normal given I used NEURON CVODE.

![iv_trace_points](https://cloud.githubusercontent.com/assets/18575092/25271733/6f74042e-2685-11e7-8963-019c25159941.png)

**Comment by wvangeit** [comment]
Ok. But so what is exactly wrong ? The voltage_deflection looks fairly correct. You might want to use 
voltage_deflection_vb_ssse to get the exact value between voltage_base and steady_state_voltage_stimend.
The voltage_deflection_begin is based on the average voltage in the beginning of the stimulus "":[stim_end + 5% of stim length, stim_end + 5% of stim length + 10% of stim length]. This also seems to be fairly correct. Maybe you wanted the peak deflection at the beginning ?
This we would need to implement in a new feature

**Comment by elisabettai** [comment]
Ok, thanks, I am fine with "voltage_deflection". Looking at the eFeatures description, I was expecting "voltage_deflection_begin" to be the difference between the absolute minimum and "voltage_base"(orange arrow), so the peak deflection at the beginning as you suggested:

![voltage_features](https://cloud.githubusercontent.com/assets/18575092/25283211/46cababc-26b3-11e7-8e00-47baa4a06784.png)

I guess this measure can be more useful to characterise the voltage "sag", given for example by the activation of the I<sub>H</sub> current.

**Comment by wvangeit** [comment]
Ok.
Could you open a new issue with a (so detailed as possible) description of the feature you want ?
(Like between which points to measure the peak, what do when there is a positive current, etc)
